### ISSUE TITLE
Support for version 0.11?

### ISSUE THREAD

**Issue by angelsk** [proget-hq/phpstan-phpspec#9]
Just looking into using this... but not compatible with the latest version.  Understand this is open source, do you know how much time an upgrade would be?

**Comment by akondas** [comment]
At this moment it is difficult to determine, phpstan changes are very unstable, lots of internal components changes ... I will let you know in this thread if there is an update ready

**Comment by marmichalski** [comment]
This has been added today in #10 thanks to magnificent by @akondas. 🏆

**Comment by akondas** [comment]
Will be released today in `0.2.0`

**Comment by akondas** [comment]
So it is now official :dancer: 
https://github.com/proget-hq/phpstan-phpspec/releases/tag/0.2.0
